### ISSUE TITLE
FoBiS tries to compile emacs backups

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#41] opened 2015-02-27 03:26 UTC
I’m getting some weird errors if there are Emacs backup files in the source directories. These files have the formats:
 - `file_name.f90~`
 - `#file_name.f90#`

It would be great if FoBiS just ignored these… are at least provided a way to tell it to ignore files matching `*.f90~` and `\#*.f90\#`

**Comment by szaghi** [comment] 2015-02-27 04:58
Should be quite easy. For files there is -exclude option, but it does not
accept wildcard. Later in the morning I can add an option for
extension/wildcard. However, it is strange that it tries to build them,
.f90- is not a default fortran extension...

**Comment by zbeekman** [comment] 2015-02-27 05:58
well to be honest, I’m not sure what exactly happens, but whatever it is, it’s bad… it could also have to do with robodoc, to be honest…. now that I think of that… I’ll investigate in the morning, it’s getting quite late here and my mental capacity is rapidly diminishing.

**Comment by szaghi** [comment] 2015-02-27 07:46
Indeed, I think the problem can be related to the `in` function of python: it return true also for partial matching, I am now changing with a more correct regex for extension checking. Give few hours.

See you soon.

**Comment by szaghi** [comment] 2015-02-27 16:27
Hi Izaak,

I am sorry for my delay. 

I have deeply tested this issue, but I was not able to reproduce your problem. 

In the unittest [build12](https://github.com/szaghi/FoBiS/tree/master/src/unittest/python/build-test12) you can see that there are correct file (`.f90`) and files that should not be compiled (`.f90~`, and `#*.f90#`), and building is right (e.g. see [tavis log](https://travis-ci.org/szaghi/FoBiS/jobs/52439882) line 712). I close this issue, but if you can provide me an example raising the bug I will reopen it.

See you soon.

P.S. into the new version just uploaded I have added some trivial support for coverage analysis (presently with only gfortran): for example see [BeFoR64](https://github.com/szaghi/BeFoR64). My .travis.yml is still bugged: the cpp-coveralls does not upload the coverage analysis data, I have to upload them explicitly from my local repo, but this is not related to FoBiS.py.

**Closed by szaghi** 2015-02-27 16:27 UTC

**Comment by zbeekman** [comment] 2015-02-27 16:57
Yeah, I’m pretty sure it was caused by robodoc, I’ll let you know if I find an example where that is not the case… otherwise, I agree that we can close it.
