### ISSUE TITLE
FoBiS.py no longer working after upgrade!

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#38] opened 2015-02-18 18:02 UTC
I just upgraded FoBiS.py using:
```bash
$ sudo pip install --upgrade FoBiS.py
```
The upgrade seemed to proceed without incident.

Then, I tried to build something and got the following errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/FoBiS.py", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/fobis/fobis.py", line 142, in main
    build()
  File "/usr/local/lib/python2.7/site-packages/fobis/fobis.py", line 85, in build
    builder.build(file_to_build=pfile, output=__config__.cliargs.output, nomodlibs=nomodlibs, mklib=__config__.cliargs.mklib)
  File "/usr/local/lib/python2.7/site-packages/fobis/Builder.py", line 414, in build
    result = syswork(link_cmd)
  File "/usr/local/lib/python2.7/site-packages/fobis/utils.py", line 20, in syswork
    return [error, str(output.decode("utf-8"))]
UnicodeEncodeError: ‘ascii’ codec can't encode character u'\u2019' in position 25: ordinal not in range(128)
```

It seems that \u2019 is the unicode character “RIGHT SINGLE QUOTATION MARK” Any thoughts on what is going wrong? I’m wondering if I should try downgrading to get rid of this error

**Comment by szaghi** [comment] 2015-02-18 18:49
Oh no! This is very strange. I will fix it tomorrow. This error happen with also the 1.4.3?

**Comment by zbeekman** [comment] 2015-02-18 21:09
@szaghi to be honest, I have no idea about 1.4.3, I skipped 1.3.1 to the most recent version on pip/PyPi. I have since then downgraded back to 1.3.1

If you need me to I can try to run a few experiments with different versions… but hopefully that won’t be needed.

**Comment by szaghi** [comment] 2015-02-19 05:04
Hi Izaak, 
Can you send me the example raising the bug or at least the command line invocation of FoBiS? My unittests work all...

Thank you

**Comment by szaghi** [comment] 2015-02-19 10:47
Hi Izaak,

I have just pushed the new version 1.5.1 with some bug fixes and improvements, but I was not able to reproduce your issue. Please, give me more details or a bug-raising example.

See you soon.

**Comment by zbeekman** [comment] 2015-02-19 13:17
OK, I’ll try to work on this this afternoon or evening

**Comment by szaghi** [comment] 2015-02-19 13:19
Thank you very much, your help is greatly appreciated.

**Comment by zbeekman** [comment] 2015-02-21 21:26
I wonder if this has to do with the ‘space before quote’ arg parse bug… Will try messing around with it.

**Comment by szaghi** [comment] 2015-02-27 16:28
I am closing this, but I will reopen as soon as I find an example raising the bug.

**Closed by szaghi** 2015-02-27 16:28 UTC
Labels: bug

**Comment by zbeekman** [comment] 2015-02-27 17:00
OK. I have restructured the code that was causing this to happen (for other reasons) and everything seems to work well, at least for now. I’ll reopen if I run into the problem again, otherwise, I agree, close the issue.
