### ISSUE TITLE
Python 3 crash

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#102] opened 2018-04-20 10:14 UTC
I think the latest release is broken on Python 3:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/FoBiS.py", line 21, in <module>
    main()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/fobis.py", line 45, in main
    run_fobis()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/fobis.py", line 71, in run_fobis
    run_fobis_build(configuration)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/fobis.py", line 88, in run_fobis_build
    pfiles = parse_files(configuration=configuration)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/fobis.py", line 264, in parse_files
    pfile.parse(inc=configuration.cliargs.inc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/ParsedFile.py", line 327, in parse
    self.doctest.parse(source=source)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/fobis/Doctest.py", line 67, in parse
    for line in source.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

2.2.8 worked, but 2.2.9.1 is crashing with Python 3.5 and 3.6.

**Comment by szaghi** [comment] 2018-04-20 13:26
Hi @jacobwilliams 

thank you for the report. 

The latest release is unstable, I have to fix it quickly, my bad. I, try to dig deeper later today.

**Comment by szaghi** [comment] 2018-04-20 14:31
Hi @jacobwilliams 

I have just pushed the version 2.9.2 that is intended to be a stable release with fix for the previously introduced cpp dependency and with a fix for your python 3 bug.

Please, let me know if the fixes work fo you.

Cheers.

**Comment by jacobwilliams** [comment] 2018-04-20 15:16
I still get the same error.

```
...
line 67, in parse
    for line in str(source.split('\n')):
TypeError: a bytes-like object is required, not 'str'
```
with:
```
$ FoBiS.py --version
FoBiS.py 2.9.2

$ python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

```

**Comment by szaghi** [comment] 2018-04-20 15:26
Arghhhh.... this is a problem, I am not able to reproduce it now...

```bash
┌╼ stefano@zaghi(05:18 PM Fri Apr 20) on master
├───╼ ~/python/FoBiS/src/unittest/python/build-test13 5 files, 32Kb
└──────╼ FoBiS.py build
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: src/nested-1/nested-2
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c -Og -ftest-coverage -fprofile-arcs -pg -fopenmp -Dtest"
    Linking flags: "-Og -fprofile-arcs -pg -fopenmp"
    Preprocessing flags: "-Dtest"
    Coverage: True
      Coverage compile and link flags: ['-ftest-coverage -fprofile-arcs', '-fprofile-arcs']
    Profile: True
      Profile compile and link flags: ['-pg', '-pg']
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building src/cumbersome.f90
Compiling src/nested-1/first_dep.f90 serially
Executing: gfortran -c -Og -ftest-coverage -fprofile-arcs -pg -fopenmp -Dtest -J mod -Imod -Isrc/nested-1/nested-2 src/nested-1/first_dep.f90 -o obj/first_dep.o
Compiling src/cumbersome.f90 serially
Executing: gfortran -c -Og -ftest-coverage -fprofile-arcs -pg -fopenmp -Dtest -J mod -Imod -Isrc/nested-1/nested-2 src/cumbersome.f90 -o obj/cumbersome.o
Linking ./build-test13
Executing: gfortran  -Og -fprofile-arcs -pg -fopenmp -J mod obj/cumbersome.o obj/first_dep.o  -o ./build-test13
Target src/cumbersome.f90 has been successfully built

┌╼ stefano@zaghi(05:18 PM Fri Apr 20) on master [?]
├───╼ ~/python/FoBiS/src/unittest/python/build-test13 7 files, 68Kb
└──────╼ FoBiS.py --version
Module 'pygooglechart' not found: Gcov graphs disabled
FoBiS.py 2.9.2

┌╼ stefano@zaghi(05:18 PM Fri Apr 20) on master [?]
├───╼ ~/python/FoBiS/src/unittest/python/build-test13 7 files, 68Kb
└──────╼ python --version
Python 3.6.4
```

as you can see the new version with python 3.6.4 works fine in my env.

Does this crash happens for building all codes, or only for a specific case? Maybe, there is something that my tests suite still not cover.

The difference of the new version with respect older should be only in the *doctests* contained into sources that must be preprocessed (in file having upper case extension). Thus, I cannot figure out why older version works and the new one not...

**Comment by jacobwilliams** [comment] 2018-04-20 16:13
It does work with some projects (for example it works with [bspline-fortran](https://github.com/jacobwilliams/bspline-fortran) but not for others (doesn't work for [json-fortran](https://github.com/jacobwilliams/json-fortran)). For example, in JSON-Fortran, if you run:
```
./build.sh --compiler intel
```
I get the same error. Note that JSON-Fortran does have proprocessed files, but the other one doesn't.

**Comment by szaghi** [comment] 2018-04-23 13:33
@jacobwilliams 

A new tentative to fix it is only, v2.9.3. 

Let me know if this time has been the right time...

Cheers

P.S. python 3 vs python 2 is a PITA

**Comment by jacobwilliams** [comment] 2018-04-23 17:17
Seems to work for me now. Thanks!

**Comment by szaghi** [comment] 2018-04-24 07:41
@jacobwilliams you are much more than welcome!

I am closing this issue, feel free to reopen it if you find other related-bugs.

Cheers.

**Closed** 2018-04-24 07:41 UTC
Labels: bug
